spring:
  datasource:
    url: jdbc:mysql://192.168.3.186/dpa_seata?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: OcFPntqQb2W
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 10
    host: 192.168.3.186
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
    password: OcFPntqQb2W

management:
  endpoints:
    web:
      exposure:
        include: "*"

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

seata:
  registry:
    type: nacos
    nacos:
      cluster: default
      namespace: dpa-seata
      server-addr: 192.168.3.183:8848
      group: dpa-seata
  config:
    nacos:
      namespace: dpa-seata
      server-addr: 192.168.3.183:8848
      group: dpa-seata
      data-id: seataServer.properties
    type: nacos
  enabled: true
  tx-service-group: goods_tx_group
  service:
    vgroup-mapping:
      goods_tx_group: default
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT