spring:
  datasource:
    url: jdbc:mysql://192.168.3.83/devops-lyx?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123qweASD
    driver-class-name: com.mysql.cj.jdbc.Driver
  # LDAP连接配置
  ldap:
    urls: ldap://192.168.1.98
    base: DC=jktest,DC=cn
    username: administrator
    password: Adadmin@jk888

  redis:
    database: 11
    password: OcFPntqQb2W
    host: 192.168.3.186
    port: 6379
    timeout: 100000

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30