spring:
  datasource:
    url: jdbc:mysql://192.168.3.186/dpa_yanxin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: OcFPntqQb2W
    driver-class-name: com.mysql.cj.jdbc.Driver
  # LDAP连接配置
#  ldap:
#    urls: ldap://192.168.1.98
#    base: DC=jktest,DC=cn
#    username: administrator
#    password: Adadmin@jk888
management:
  endpoints:
    web:
      exposure:
        include: "*"

#  redis:
#    host: 192.168.6.70
#    port: 6379
#    database: 11
#    password: 123456
#    timeout: 30000
#    jedis:
#      pool:
#        max-active: 256
#        max-wait: 30000
#        max-idle: 64
#        min-idle: 32
#    cluster:
#      nodes: 192.168.6.70:6379,192.168.6.71:6379,192.168.6.72:6379

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30