spring:
  datasource:
    url: jdbc:mysql://192.168.3.186/dpa_yanxin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: OcFPntqQb2W
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # LDAP连接配置
  ldap:
    urls: ldap://192.168.1.98
    base: DC=jktest,DC=cn
    username: administrator
    password: Adadmin@jk888
  redis:
    database: 10
    password: OcFPntqQb2W
    host: 192.168.3.186
    port: 6379

  elasticsearch:
    rest:
      # uris: es.test.jkservice.org:9200
      uris: 192.168.3.183:9200
      username: elastic
      password: jkstack


  rabbitmq:
    username: admin
    password: OcFPntqQb2W
    host: 192.168.3.186
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 2
          initial-interval: 3000
      direct:
        acknowledge-mode: manual
        prefetch: 1

#    ssl:
#      enabled: true
#      keyStore: classpath:client_key.p12
#      keyStoreType: PKCS12
#      keyStorePassword: ''
#      trustStore: classpath:rabbitstore
#      trustStoreType: JKS
#      trustStorePassword: jkstack
#      algorithm: TLSv1.2
#      verifyHostname: false
#      validate-server-certificate: false


management:
  endpoints:
    web:
      exposure:
        include: "*"


#    cluster:
#      nodes: 192.168.6.70:6379,192.168.6.71:6379,192.168.6.72:6379

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

seata:
  registry:
    type: nacos
    nacos:
      cluster: default
      namespace: dpa-seata
      server-addr: 192.168.3.183:8848
      group: dpa-seata
  config:
    nacos:
      namespace: dpa-seata
      server-addr: 192.168.3.183:8848
      group: dpa-seata
      data-id: seataServer.properties
    type: nacos
  enabled: true
  tx-service-group: goods_tx_group
  service:
    vgroup-mapping:
      goods_tx_group: default
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT