spring:
  datasource:
    url: jdbc:mysql://192.168.3.186/dpa_yanxin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: OcFPntqQb2W
    driver-class-name: com.mysql.cj.jdbc.Driver
camunda:
  bpm:
    admin-user:
      first-name: demo
      id: demo
      password: demo
    filter:
      create: ALL tasks
server:
  port: 8080
